# -*- coding: utf-8 -*-
"""nlp-pdf-question-answering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xWUKkLol0-yTr858L9XYmHVRGf77nSO1
"""

!pip -q install pymupdf
!pip -q install sentence-transformers
!pip -q install faiss-cpu
!pip -q install nltk

import fitz
import faiss
import nltk
import numpy as np

from sentence_transformers import SentenceTransformer

nltk.download("punkt")

from google.colab import files

uploaded = files.upload()

filename = list(uploaded.keys())[0]

doc = fitz.open(filename)

text = ""

for page in doc:
    text += page.get_text()

doc.close()

print(text[:1000])

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

from nltk.tokenize import sent_tokenize

sentences = sent_tokenize(text)

chunks = []

chunk = ""

for sentence in sentences:

    if len(chunk) < 400:
        chunk += " " + sentence
    else:
        chunks.append(chunk)
        chunk = sentence

chunks.append(chunk)

print("Total Chunks:", len(chunks))

model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(chunks)

embeddings = np.array(
    embeddings,
    dtype="float32"
)

print(embeddings.shape)

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(embeddings)

print("Chunks Indexed:", index.ntotal)

question = input("Ask a question about the PDF:\n")

query_vector = model.encode(
    [question]
).astype("float32")

distances, indices = index.search(
    query_vector,
    k=3
)

print("Most Relevant Sections:\n")

for idx in indices[0]:
    print(chunks[idx])
    print("-" * 80)

print("Search Results:\n")

for rank, idx in enumerate(indices[0]):
    print(f"Rank {rank+1}")
    print("Distance:", distances[0][rank])
    print()